# Be sure to restart your server when you modify this file.

# Your secret key is used for verifying the integrity of signed cookies.
# If you change this key, all old signed cookies will become invalid!

# Make sure the secret is at least 30 characters and all random,
# no regular words or you'll be exposed to dictionary attacks.
# You can use `rake secret` to generate a secure secret key.

# Make sure the secrets in this file are kept private
# if you're sharing your code publicly.

development:
  secret_key_base: 5647ba6dfc7f345c2ff11eefa2f0bd4f8b498912c49dc31a22fefb0c80f78ca835fdb9fcb51b9d584eb326ed8aaaed35e2538bef1552c99bd5935303b204fec6

test:
  secret_key_base: 0059a5608b0d3128aa576af8821f32eda7aca85ef0cfcd612dee798d6c04c7a1fb38e949c63d058eef9ae7a5e569d84f78d65352784c9f08f5674e7f29715067

# Do not keep production secrets in the repository,
# instead read values from the environment.
production:
  secret_key_base: <%= ENV["SECRET_KEY_BASE"] %>
